project:
  type: manuscript
  output-dir: docs
  render:
    - "!*.md"
  post-render:
    - "cp -rnv schema/. docs/schema/"
manuscript:
  article: index.qmd
format:
  html:
    code-line-numbers: false
    number-sections: true
    css: style.css
    highlight-style: kate
    code-copy: false  # there is try-out button instead
    syntax-definitions:
     - pg.xml
     - ebnf.xml
    include-in-header:
      text: '<script type="text/javascript" src="script.js"></script>'
    crossref:
      lst-prefix: "Example"
      lst-title: "Example"
  # requires install  texlive-fonts-extra
  pdf:
    documentclass: scrreprt
    papersize: a4paper
    toc: true
    toc-depth: 2    
    keep-tex: true
    number-sections: true
    fontsize: 11pt
    classoption:
      - DIV=14
      - BCOR=10mm
    template-partials:
      - title.tex
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}

