project:
  type: manuscript
  output-dir: docs
  render:
    - "!*.md"
  post-render:
    - "cp -rnv schema/. docs/schema/"
manuscript:
  article: index.qmd
format:
  html:
    number-sections: true
    code-line-numbers: false
    css: style.css
    highlight-style: kate
    code-copy: false  # there is try-out button instead
    syntax-definitions:
     - pg.xml
     - ebnf.xml
    include-in-header:
      text: '<script type="text/javascript" src="script.js"></script>'
    crossref:
      lst-prefix: "Example"
      lst-title: "Example"
  # requires install  texlive-fonts-extra
  pdf:
    number-sections: true
    highlight-style: kate
    syntax-definitions:
     - pg.xml
     - ebnf.xml
    documentclass: scrartcl
    papersize: a4paper
    toc: true
    toc-depth: 2    
    keep-tex: true
    fontsize: 11pt
    classoption:
     - DIV=14
     - BCOR=0mm
     - headings=standardclasses
    fig-pos: "H"
    crossref:
      lst-prefix: "Example"
      lst-title: "Example"
    template-partials:
     - title.tex
    include-in-header:
      text: |
        \usepackage{orcidlink}
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
        \AtBeginDocument{
          \definecolor{shadecolor}{RGB}{233,233,233}
          \floatstyle{plaintop}
          \captionsetup[codelisting]{font=small,labelfont=bf,singlelinecheck=false,justification=justified}
          \setlength{\abovecaptionskip}{-2mm}
          \restylefloat{codelisting}
          \floatplacement{codelisting}{H}
          \AtEndEnvironment{codelisting}{\vspace*{-6mm}}
        }
  
